app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['middleware' => 'auth'], function () {
Route::get('/home', 'HomeController@index');

Route::resource('alumnos','alumnoController');
//datatables alumnos
Route::resource('adminalumnos','adminalumnosContipos_pagostroller');
Route::post('alumnos/delete', 'alumnoController@delete');
Route::get('alumnos/view', 'alumnoController@view');
Route::get('findAlumnosNombres', 'alumnoController@findAlumnosNombres');
Route::get('findAlumnosCursos', 'alumnoController@findAlumnosCursos');


//Route::get('alumnos/search','alumnoController@search'); -- no funciona js

Route::resource('cursos_alumnos','cursos_alumnosController');

//javascript
//Route::resource('tipos_pagos','alumnos_cursosController');
//Route::resource('cursos_de_alumnos', 'cursos_de_alumnosController');

Route::get('cursos_de_alumnos/view', 'cursos_de_alumnosController@view');

Route::get('alumnos_cursos', 'alumnos_cursosController@index');
Route::post('alumnos_cursos', 'alumnos_cursosController@add');
Route::post('alumnos_cursos/create', 'alumnos_cursosController@create');
Route::get('alumnos_cursos/view', 'alumnos_cursosController@view');
Route::post('alumnos_cursos/update', 'alumnos_cursosController@update');
Route::post('alumnos_cursos/delete', 'alumnos_cursosController@delete');



Route::get('cursos', 'cursosController@index');
Route::post('cursos', 'cursosController@add');
Route::get('cursos/view', 'cursosController@view');
Route::post('cursos/update', 'cursosController@update');
Route::post('cursos/delete', 'cursosController@delete');


Route::get('usuario', 'usuariosController@index');
Route::post('usuario', 'usuariosController@add');
Route::get('usuario/view', 'usuariosController@view');
Route::post('usuario/update', 'usuariosController@update');
Route::post('usuario/delete', 'usuariosController@delete');

Route::resource('pagos_usuarios', 'usuarios_pagosController');
Route::get('pagos', 'pagosController@index');
Route::post('pagos', 'pagosController@add');
Route::get('pagos/view', 'pagosController@view');
Route::get('alumnos/autocomplete', 'alumnoController@bscautomplete');
//select 2
Route::get("autocomplete",array('as'=>'autocomplete','uses'=> 'pagosController@autocomplete'));
Route::get('select2-autocomplete-ajax', 'alumnoController@dataAjax');
//on select change
Route::post("select-ajax", array('as'=>'select-ajax','uses'=>'pagosController@selectAjax'));

Route::resource('pago/detalles', 'view_detalle_pagosController');
Route::get('pago/detalles/view', 'view_detalle_pagosController@view');

Route::resource('pago_alumnos', 'alumno_pagosController');
//reporte todos los alumnos activos
Route::get('pdf', 'PdfController@invoice');
//reporte de constancia de pago
Route::get('constanciapago', 'pagosController@constanciapago');
//reporte de todos los alumnos de una jornada
Route::get('alumnos_jornadas', 'alumno_jornadasController@alumnos_jornadas');



Route::get('tipos_pagos', 'tipo_pagoController@index');
Route::post('tipos_pagos', 'tipo_pagoController@add');
Route::post('tipos_pagos/create', 'tipo_pagoController@create');
Route::get('tipos_pagos/view', 'tipo_pagoController@view');
Route::put('tipos_pagos/update', 'tipo_pagoController@update');
Route::put('tipos_pagos/delete', 'tipo_pagoController@delete');


Route::get('establecimiento', 'establecimientoController@index');
Route::post('establecimiento', 'establecimientoController@add');
Route::get('establecimiento/view', 'establecimientoController@view');
Route::post('establecimiento/update', 'establecimientoController@update');
Route::post('establecimiento/delete', 'establecimientoController@delete');
// cursos_tipos_pagos
Route::get('cursos_tipos_pagos', 'cursos_tipos_pagosController@index');
Route::post('cursos_tipos_pagos', 'cursos_tipos_pagosController@add');
Route::get('cursos_tipos_pagos/view', 'cursos_tipos_pagosController@view');
Route::post('cursos_tipos_pagos/update', 'cursos_tipos_pagosController@update');
Route::post('cursos_tipos_pagos/delete', 'cursos_tipos_pagosController@delete');

Route::get('salon', 'SalonController@index');
Route::post('salon', 'SalonController@add');
Route::get('salon/view', 'SalonController@view');
Route::post('salon/update', 'SalonController@update');
Route::post('salon/delete', 'SalonController@delete');


Route::post('addcursosAlumnos', 'alumnoCursoController@add');
});


Route::resource('rptconstancia','apiconstaciaPagoController', ['only'=>['index','store','show','update','destroy']]);



Route::auth();

app/Http/Controllers/adminalumnosController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\model\alumnos_cursos\alumnos_cursos;
use App\model\alumno\alumno;

class adminalumnosController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $alumnos = alumno::all();
        return View('adminalumnos.index')->with('alumnos',$alumnos);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/adminalumnos/index.blade.php
@extends('layouts.app')







@section('content')

<meta name="csrf-token" content="{{ csrf_token() }}" />


  

<div class="container">

    <div class="row">

    <div class="col-md-3">

     <!-- Sidebar -->

    @include('menus.menuadmin')

    </div>

        <div class="col-md-8 ">
        <div class="container">
        <div class="row">
        <div class="col-xs-12 col-md-8">
              <h1 class="page-header text-center">ALUMNOS DISPONIBLES </h1>
              </div>
              <div class="col-xs-12 col-md-2">
             
        </div>
        </div>
        </div>
            <center>
            {!!link_to_route('alumnos.create', $title = "Nuevo Alumno", $parameters = null, $attributes = ['class'=>'btn btn-primary fa fa-plus fa fa-user'])!!}

            </center>

   
            @include('partials.messages')


            @if(count($alumnos) == 0)

              <p class="text-info">

                No se han registrado alumnos aun.

              </p>

            @else
          




                <div class="table-responsive">

                  <table class="table table-hover table-bordered" id="MyTable">

                    <thead>

                      <tr>

                        <th>

                          NO

                        </th>

                        <th>

                          NOMBRES


                        </th>

                        <th>

                          TELEFONO 

                        </th>

                        <th>

                          OPCIONES

                        </th>

                      </tr>

                    </thead>

                    <tbody id="datosAlumnos">

                      @foreach($alumnos as $key => $rol)

                        <tr>

                          <td>

                            {{ $rol->id }}

                          </td>

                          <td>

                            {{ mb_strtoupper($rol->nombre) }} {{ mb_strtoupper($rol->apellido) }}

                          </td>

                         <td>

                            {{ mb_strtoupper($rol->telefono) }}

                          </td>

                         <td>
                         <input type="hidden" name="hidden_delete" id="hidden_delete" value="{{url('alumnos/delete')}}">

                          <input type="hidden" name="hidden_view" id="hidden_view" value="{{url('alumnos/view')}}">

                         

                          

                            {!!link_to_route('alumnos.edit', $title = 'Modificar', $parameters = $rol->id, $attributes = ['class'=>'btn btn-warning fa fa-edit'])!!}

                        

                            {!!link_to_route('alumnos.show', $title = 'Detalles', $parameters = $rol->id, $attributes = ['class'=>'btn btn-info fa fa-eye'])!!}




                            <button class="btn btn-danger btn-sm" onclick="fun_delete('{{$rol -> id}}')"><span class="fa fa-times"> </span> Eliminar</button>



                          </td>



                        





                        </tr>



                      @endforeach



                    </tbody>




                  </table>


                </div>
                <link href="{{ url('/') }}/css/dataTables.bootstrap.min.css" rel="stylesheet" type="text/css">

                 
                 <link rel="stylesheet" type="text/css" href="http://cdn.datatables.net/1.10.15/css/jquery.dataTables.css">
                <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
                <script src="//code.jquery.com/jquery-2.1.3.min.js"></script>
                <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.2/jquery.js"></script>

                <script language="javascript" type="text/javascript">
                                    
                    $(document).ready(function () {
                      $('#MyTable').DataTable();
                  } );
                </script>


                  {!!Form::hidden('_token', csrf_token(), ['id'=>'token'])!!}





            @endif







          </div>



          <!-- /.col-lg-12 -->



      </div>

      





  </div>






@endsection